In [30]:
from pandas.io.json import json_normalize
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

In [31]:
config = json.loads(open('combinedArray.json').read())

In [32]:
favLang = json_normalize(config)

In [35]:
favLang

,age.20-24,age.25-29,age.30-34,age.35-39,age.40-44,age.45-49,age.50 and over,age.under 20,city,country,favLanguage,gender,nativeLanguage,programmingExperience.months,programmingExperience.years
0,0,0,0,0,0,0,0,1,New Delhi,India,swift,m,hindi,0,2
1,0,0,1,0,0,0,0,0,London,England,Ruby,m,English,4,1
2,1,0,0,0,0,0,0,0,Dhaka,Bangladesh,JavaScript,m,Bangla,6,1
3,0,1,0,0,0,0,0,0,Vancouver,Canada,python,f,english,0,3
4,1,0,0,0,0,0,0,0,"Nanded, Pune",India,Javascript,m,Hindi,4,0
5,1,0,0,0,0,0,0,0,Espoo,Helsinki,Javascript,m,Nepali,2,2
6,0,0,0,0,0,0,0,1,Worcester,United States,Go,na,English,0,4
7,0,1,0,0,0,0,0,0,Glasgow,United Kingdom,Javascript,m,English,6,0
8,0,0,0,0,0,0,0,1,Bhubaneswar,India,Java,m,Bengali,3,4
9,1,0,0,0,0,0,0,0,Bengaluru,India,C#,m,Malayalam,0,5
10,1,0,0,0,0,0,0,0,New Delhi,India,Python,m,Hindi,6,2
11,1,0,0,0,0,0,0,0,Chennai,India,JAVA,m,Tamil,0,2
12,0,0,0,0,0,0,0,1,Allahabad,India,Python,m,hindi,6,3
13,1,0,0,0,0,0,0,0,Pune,India,JavaScript,m,Marathi,6,3
14,1,0,0,0,0,0,0,0,Dublin,CA,JS,m,English,0,5
15,1,0,0,0,0,0,0,0,Seattle,USA,Javascript - NodeJS,m,English,0,4
16,1,0,0,0,0,0,0,0,Burlington,Canada,Rust <rust-lang.org>,m,English,6,12
17,0,0,0,0,0,0,1,0,Vienna,Austria,Java,m,German,1,33
18,0,1,0,0,0,0,0,0,Putnam Valley,USA,Javascript,m,English,10,3
19,0,1,0,0,0,0,0,1,Bhopal,India,Java,m,Hindi,2,1
20,0,0,0,0,0,1,0,0,Columbus,USA,Ruby,m,English,7,15
21,0,1,0,0,0,0,0,0,Granada,Spain,ECMAScript 6,m,Spanish,2,5
22,0,0,0,1,0,0,0,0,Split,Croatia,PHP,m,croatian,4,1
23,1,0,0,0,0,0,0,0,London,United Kingdom,Python,m,Arabic,0,6
24,1,0,0,0,0,0,0,0,Parnaíba,Brasil,C++,m,Portuguese,2,3
25,1,0,0,0,0,0,0,0,Bursa,Turkey,C++,m,turkish,3,4
26,1,0,0,0,0,0,0,0,Hortolândia,São Paulo,PHP,m,Brazilian Portuguese,6,1
27,0,0,0,0,0,0,0,1,Vadodara,India,JavaScript,m,hindi,0,2
28,0,1,0,0,0,0,0,0,San Vicente,El Salvador,JavaScript,m,Spanish,6,2
29,1,0,0,0,0,0,0,0,Yogyakarta,Indonesia,Javascript,m,Indonesia,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,0,1,0,0,0,0,0,NaN,Portland,USA,C++,f,English,6,8
34,0,1,0,0,0,0,0,0,Vancouver,Canada,python,f,english,0,2
35,1,0,0,0,0,0,0,0,Amsterdam,Netherland,Java,f,Danish,1,1
36,1,0,0,0,0,0,0,0,Mexico City,Mexico,Kotlin,m,Spanish,9,4
37,1,0,0,0,0,0,0,0,Baton Rouge,United States,c++,na,English,0,5
38,1,0,0,0,0,0,0,0,London,UK,Ruby,m,English,3,2
39,1,0,0,0,0,0,0,0,Nittambuwa,Sri Lanka,PHP,m,sinhala,0,3
40,1,0,0,0,0,0,0,0,New York,United States,C,m,english,0,6
41,0,1,0,0,0,0,0,0,Zagreb,Croatia,Java,f,Croatian,0,4
42,0,1,0,0,0,0,0,0,Brasília,Brazil,javascript,m,brazilian portuguese,10,2
43,1,0,0,0,0,0,0,0,Munich,Germany,swift,f,albanian,0,4
44,1,0,0,0,0,0,0,0,Montreal,Canada,ES6,m,French,10,4
45,0,1,0,0,1,0,0,0,Los Angeles,USA,bash,m,English,0,3
46,0,1,0,0,0,0,0,0,Toronto,Canada,python,m,English,2,1
47,0,0,1,0,0,0,0,0,Los Angeles,USA,Go,m,English,0,2
48,1,0,0,0,0,0,0,0,Bonn,Germany,python,m,German,5,6
49,1,0,0,0,0,0,0,0,Weligama,Sri Lanka,Java,m,Tamil,3,5
50,0,0,0,1,0,0,0,0,Stord,Norway,Python,m,Norwegian,10,5
51,,0,0,1,0,0,0,0,Waterloo,United States,Python,m,American,6,3
52,1,0,0,0,0,0,0,0,Anuradhapura,Sri Lanka,Actionscript,m,Sinhala,2,9
53,0,0,0,0,0,0,0,1,Ghaziabad,India,python,m,hindi,0,9
54,0,1,0,0,0,0,0,0,Parnaíba,Brazil,Python,m,Portuguese,6,0
55,0,1,0,0,0,0,0,0,Vancouver,Canada,Python,m,English,2,6
56,0,1,0,0,0,0,0,0,Colombo,Sri Lanka,javascript,m,Sinhala,10,2
57,0,0,0,0,0,0,0,1,Kochi,India,swift,m,hindi,0,2
58,1,0,0,0,0,0,0,0,Edwardsville,USA,python,f,English,10,2
59,0,1,0,0,0,0,0,NaN,Shinjuku,Japan,Python,f,English,1,2
60,0,1,0,0,0,0,0,0,Saint Petersburg,Russian Federation,Python,m,Russian,8,4
61,0,0,0,0,0,0,0,1,Mumbai,India,Python,m,Hindi,10,0
62,0,1,0,0,0,0,0,0,Irvine,United States of America,Python,f,English,7,0

In [37]:
favLang = favLang[['city', 'country', 'favLanguage', 'gender', 'nativeLanguage', 'programmingExperience.years', 'programmingExperience.months']]

In [38]:
favLang

,city,country,favLanguage,gender,nativeLanguage,programmingExperience.years,programmingExperience.months
0,New Delhi,India,swift,m,hindi,2,0
1,London,England,Ruby,m,English,1,4
2,Dhaka,Bangladesh,JavaScript,m,Bangla,1,6
3,Vancouver,Canada,python,f,english,3,0
4,"Nanded, Pune",India,Javascript,m,Hindi,0,4
5,Espoo,Helsinki,Javascript,m,Nepali,2,2
6,Worcester,United States,Go,na,English,4,0
7,Glasgow,United Kingdom,Javascript,m,English,0,6
8,Bhubaneswar,India,Java,m,Bengali,4,3
9,Bengaluru,India,C#,m,Malayalam,5,0
10,New Delhi,India,Python,m,Hindi,2,6
11,Chennai,India,JAVA,m,Tamil,2,0
12,Allahabad,India,Python,m,hindi,3,6
13,Pune,India,JavaScript,m,Marathi,3,6
14,Dublin,CA,JS,m,English,5,0
15,Seattle,USA,Javascript - NodeJS,m,English,4,0
16,Burlington,Canada,Rust <rust-lang.org>,m,English,12,6
17,Vienna,Austria,Java,m,German,33,1
18,Putnam Valley,USA,Javascript,m,English,3,10
19,Bhopal,India,Java,m,Hindi,1,2
20,Columbus,USA,Ruby,m,English,15,7
21,Granada,Spain,ECMAScript 6,m,Spanish,5,2
22,Split,Croatia,PHP,m,croatian,1,4
23,London,United Kingdom,Python,m,Arabic,6,0
24,Parnaíba,Brasil,C++,m,Portuguese,3,2
25,Bursa,Turkey,C++,m,turkish,4,3
26,Hortolândia,São Paulo,PHP,m,Brazilian Portuguese,1,6
27,Vadodara,India,JavaScript,m,hindi,2,0
28,San Vicente,El Salvador,JavaScript,m,Spanish,2,6
29,Yogyakarta,Indonesia,Javascript,m,Indonesia,2,4
...,...,...,...,...,...,...,...
33,Portland,USA,C++,f,English,8,6
34,Vancouver,Canada,python,f,english,2,0
35,Amsterdam,Netherland,Java,f,Danish,1,1
36,Mexico City,Mexico,Kotlin,m,Spanish,4,9
37,Baton Rouge,United States,c++,na,English,5,0
38,London,UK,Ruby,m,English,2,3
39,Nittambuwa,Sri Lanka,PHP,m,sinhala,3,0
40,New York,United States,C,m,english,6,0
41,Zagreb,Croatia,Java,f,Croatian,4,0
42,Brasília,Brazil,javascript,m,brazilian portuguese,2,10
43,Munich,Germany,swift,f,albanian,4,0
44,Montreal,Canada,ES6,m,French,4,10
45,Los Angeles,USA,bash,m,English,3,0
46,Toronto,Canada,python,m,English,1,2
47,Los Angeles,USA,Go,m,English,2,0
48,Bonn,Germany,python,m,German,6,5
49,Weligama,Sri Lanka,Java,m,Tamil,5,3
50,Stord,Norway,Python,m,Norwegian,5,10
51,Waterloo,United States,Python,m,American,3,6
52,Anuradhapura,Sri Lanka,Actionscript,m,Sinhala,9,2
53,Ghaziabad,India,python,m,hindi,9,0
54,Parnaíba,Brazil,Python,m,Portuguese,0,6
55,Vancouver,Canada,Python,m,English,6,2
56,Colombo,Sri Lanka,javascript,m,Sinhala,2,10
57,Kochi,India,swift,m,hindi,2,0
58,Edwardsville,USA,python,f,English,2,10
59,Shinjuku,Japan,Python,f,English,2,1
60,Saint Petersburg,Russian Federation,Python,m,Russian,4,8
61,Mumbai,India,Python,m,Hindi,0,10
62,Irvine,United States of America,Python,f,English,0,7